baseurl = "https://articles.lakurdina.com/"
title = "Lakurdina Articles"
author = "Lakurdina"
copyright = "Copyright © 2022, Lakurdina; all rights reserved."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"
enableGitInfo = true

pygmentsUseClasses=true

disqusShortname = ""
#googleAnalytics = ""

[params]
    mainSections = ["articles", "poems", "stories", ]
    dateform        = '2 Jan 2006'
    dateformShort   = '2 Jan'
    dateformNum     = '2006-01-02'
    dateformNumTime = '2006-01-02 15:04 -0700'
    author = "Lakurdina Articles"
    introDescription = "This is Lakurdina Articles: Thought-provoking writing on fascinating subjects. Here I publish work from a range of one-off and regular contributors on subjects that interest them and me."
    contentSharing = "I'm happy for you to share content on this site, but please provide attribution."

[taxonomies]
  category = 'categories'
  authors = 'authors'
  tag = 'tags'


[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]



[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "200601"


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

